### ISSUE TITLE
[8.0] ElasticSearch - local 환경 연결 및 동작테스트

### ISSUE THREAD

**Issue by Jaeminst** [Jaeminst/devops-01-Final-TeamG#60]

**Comment by Jaeminst** [comment]
Elasticsearch 생성 및 연결을 위해 다음의 과정으로 진행 
![a](https://user-images.githubusercontent.com/61172855/169990583-38249625-c9d9-4caf-8956-52fd3b63e5a9.png)


- 로그 수집(logstash) → 로그 저장(및 검색, ElasticSearch) → 모니터링(Kibana) 으로 구성되어있음.
- OpenSearch 이용않고 docker/ docker compose 이용하여 ELK 스택 구축
- github docker-ELK repo clone하여 수정 후 사용 ( https://github.com/deviantony/docker-elk)
<br><br>

# Local 환경 setting

### 필요한 파일 정리

- docker-compose.yml
- .env
- elasticsearch
    - Dockerfile
    - config
        - elasticsearch.yml
- logstash
    - Dockerfile
    - config
        - logstash.yml
    - pipeline
        - logstash.conf
- kibana
    - Dockerfile
    - config
        - kibana.yml
        
<br>

### 파일별 수정 내용

1. .env
    
    ```yaml
    # 희망버전 선택
    ELK_VERSION=8.2.0
    ```
    
2. ./elasticsearch/config/elasticsearch.yml
    
    ```yaml
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    
    ## X-Pack 관련 설정 추가(맨 아래줄)
    xpack.license.self_generated.type: basic  #무료버전
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true  
    ```
    
3. ./logstash/config/logstash.yml
    
    ```yaml
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    
    ## X-Pack 관련 설정추가 (이 부분 없으니 로그 수집 되지 않음)
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.username: username
    xpack.monitoring.elasticsearch.password: ${variable}
    ```
    

- 이렇게 수정 후 docker-compose up -d 해주고 localhost:9200 , localhost:5601접속 잘 되는지 확인
- docker logs {elasticsearch container} 로 로그 잘 쌓이는지 확인
- elastichost를 localhost로 설정해주면 연결안됨 (최초 http:elasticsearch:9200 그대로 사용하여 localhost로 테스트 가능)


<br><br>

# 변경사항

- 기존 filebeat →logstash → elasticsearch 에서 많은 error 발생
- Node 코드 직접 작성하여 서버 → elasticsearch 로 바로 가는 방식으로 변경
- test code 작성 후 document에 값 들어가는 것 확인
    
![스크린샷, 2022-05-27 09-49-53](https://user-images.githubusercontent.com/61172855/170607161-dee0d00e-84fb-4740-8344-6311382c3d6a.png)


    
- 현재는 test code, 추후에 API 구성 완료되면 그에 맞게 적용 (코드는 elasticsearch 디렉토리 참조)
